### PR TITLE
chore: Update dependencies

### PR DESCRIPTION
**Pull request by martinalbert**
Updates peer dependency `gatsby` to support versions bigger than v5. This solves the problem in [#53](https://github.com/ButterCMS/gatsbyjs-starter-buttercms/pull/53) of gatsby starter repo.

And also updates present dependencies, only major change is `prettier` to v2 that was released in 2020. More info [here](https://prettier.io/blog/2020/03/21/2.0.0.html#breaking-changes).

`npm audit` reports no vulnerabilities.

### CODE REVIEW

**Review by ViolanteCodes — COMMENTED** [review]
I think something is wrong with this PR at this time. I tried to do a fresh install (delete repo, clone repo, checkout branch, nvm into 16.14.0, and use install command from readme) and it failed with the following terminal output: 
```
maria@maria-Galago-Pro:~/Programming/butter/starters/gatsby-source-buttercms$ npm install --save gatsby-source-buttercms

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-source-buttercms@2.2.6
npm ERR! Found: gatsby@5.7.0
npm ERR! node_modules/gatsby
npm ERR!   peer gatsby@"^5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@">=2.22.3 <= 4.14.1" from gatsby-source-buttercms@2.2.6
npm ERR! node_modules/gatsby-source-buttercms
npm ERR!   gatsby-source-buttercms@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/maria/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maria/.npm/_logs/2023-02-21T14_46_26_129Z-debug-0.log
maria@maria-Galago-Pro:~/Programming/butter/starters/gatsby-source-buttercms$ ```

**Comment by martinalbert** [comment]
@ViolanteCodes the install from the readme is intended for usage of this dependency, should be ok with `npm install`. Should point out though that gatsby update to v5 requires node version 18 and higher, so you'll get warnings during install with node 16 and lower.

**Comment by ViolanteCodes** [comment]
@orlyohreally I was able to install this using the `npm install` command without conflict or issue. I do see the warnings for node 18 and want to know what you think - I am thinking that if the testing works out okay, merging this with a note in the readme specifying that it's designed for node 18 and above and then releasing a major version bump. What do you think?

**Comment by orlyohreally** [comment]
> @orlyohreally I was able to install this using the `npm install` command without conflict or issue. I do see the warnings for node 18 and want to know what you think - I am thinking that if the testing works out okay, merging this with a note in the readme specifying that it's designed for node 18 and above and then releasing a major version bump. What do you think?

Yes, sounds good. I think we should display a badge specifying node's version. I think we have some repo with it

**Comment by martinalbert** [comment]
Thanks, @ViolanteCodes and @orlyohreally, I added the Node.js version badge and updated the node engines in package.json. Also found out that warnings during installation are intentional, as discussed here: https://stackoverflow.com/a/74795155/5953479.

**Review by ViolanteCodes — APPROVED** [review]
This LGTM - was able to pull down as a local dependency for the updated starter project and get that working

**Pull request merged**
