### PR TITLE
feat: bump gatsby version to include 4.5.2

### PR DESCRIPTION
**Pull request by prokopsimek**
Bump gatsby dependency to 4.5.2. Tested. ✅

Not sure why there is package-lock.json (not updated since gatbsy v3 dependency) and also yarn.lock together. I have updated both files.

### CODE REVIEW

**Review by ViolanteCodes — APPROVED** [review]
LGTM

**Comment by jakelumetta** [comment]
Do we need to bump minor version of this package as well so we can publish new package to NPM?

**Comment by prokopsimek** [comment]
@jakelumetta Yes, it's necessary for me to be able to download the newest version. Thanks!

**Comment by jakelumetta** [comment]
@prokopsimek ok done. version 2.2.3

**Pull request merged**
